sudo: required
language: node_js
node_js:
  - "11.10.1"
services:
  - docker

before_install:
  - docker build -t vinhlee95/docker-react-sandbox -f Dockerfile.dev .

script:
  - docker run vinhlee95/docker-react-sandbox npm run test -- --coverage
