sudo: required
language: node_js
node_js:
  - "11.10.1"
services:
  - docker

before_install:
  - docker build -t vinhlee95/docker-react-sandbox -f Dockerfile.dev .

script:
  - docker run vinhlee95/docker-react-sandbox npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-sandbox"
  env: "DockerReactSandbox-env"
  bucket_name: "elasticbeanstalk-us-east-1-734739223659"
  bucket_path: "docker-react-sandbox"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
