version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # bookmark node_modules dir
      - .:/app # map pwd to the /app dir
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # bookmark node_modules dir
      - .:/app # map pwd to the /app dir
    command: ["npm", "run", "test"]
